baseURL = "https://thought-architecture.github.io/thought-architecture-hugo/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

title = "Thought Architecture"
theme = "hello-friend-ng"

[languages]

[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2

